name: First Workflow
on: workflow_dispatch
jobs:
  fisrt-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print Good Night
        run: echo "Goodnight"
