name: First Workflow

on:
  workflow_dispatch:

jobs:

  build:
    name: Mock Build
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Building the project..."

  deploy:
    name: Mock Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Step
        run: echo "Deploying the project..."
