name: Test PR Workflow

on:
  pull_request:
    branches:
      - main
      - release/uat
    paths-ignore:
      - '.github/**'   

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !contains(join(github.event.pull_request.changed_files.*), '.github/')
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Run Fake Unit Test
        run: echo "Running mock unit tests... All tests passed!"
      - name: Print Good Night
        run: echo "Goodnight"
